GET localhost:8081/posts

###

GET localhost:8081/users/2

###

POST localhost:8081/addPost
Content-Type: application/json

{
  "id" : 3,
  "likes": 12313,
  "owner": null,
  "content": "follow my inst"
}